// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amlwclyglkucfkuhjqps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbHdjbHlnbGt1Y2ZrdWhqcXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzA2OTMsImV4cCI6MjA2ODYwNjY5M30.zhd3gebWjOZXohYU4hJrbuN1O5a5RGYeKAZmubWjNOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});