
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amlwclyglkucfkuhjqps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtbHdjbHlnbGt1Y2ZrdWhqcXBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMzA2OTMsImV4cCI6MjA2ODYwNjY5M30.zhd3gebWjOZXohYU4hJrbuN1O5a5RGYeKAZmubWjNOE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Guard against invalid audit_logs inserts that spam 400s and can crash the app.
// We only intercept audit_logs; everything else is untouched.
function isUUID(str: string) {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(str);
}

const originalFrom = (supabase as any).from.bind(supabase);

(supabase as any).from = (table: string) => {
  if (table === 'audit_logs') {
    const builder: any = {};
    builder.insert = async (payload: any, options?: any) => {
      try {
        const sample = Array.isArray(payload) ? payload[0] : payload;
        const uid = sample?.user_id;
        if (uid && typeof uid === 'string' && isUUID(uid)) {
          // Valid UUID – let it go through normally
          return originalFrom('audit_logs').insert(payload, options);
        }
        // Invalid or missing UUID – suppress to avoid constant 400s
        console.warn('[Security] Suppressed audit_logs insert with non-UUID user_id:', uid);
        return { data: null, error: null };
      } catch (e) {
        console.warn('[Security] Suppressed audit_logs insert due to error:', e);
        return { data: null, error: null };
      }
    };
    // Provide harmless stubs in case any code tries to read the table in the client
    builder.select = async () => ({ data: [], error: null });
    builder.update = async () => ({ data: null, error: null });
    builder.delete = async () => ({ data: null, error: null });
    return builder;
  }
  return originalFrom(table);
};

